server:
  port: 8080
  tomcat:
      uri-encoding: UTF-8

spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/depot?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: admin
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
#    http:
#        encoding:
#            force: true
#            charset: UTF-8
#            enabled: true
#    devtools:
#        restart:
#          enabled: true
#          additional-paths: src/main/java/com
mybatis:
  #mapper-locations: classpath:mapping/*.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jobs.model
  #type-aliases-package: com.winter.model

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql